PostgreSQL:
  image: postgres
  restart: always
  ports:
    - "5432:5432"

  environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: sharepool
    POSTGRES_DB: SharePool

  volumes:
    - /docker/postgresql:/var/lib/postgresql