version: '3.4'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sharepool
      POSTGRES_DB: SharePool

    volumes:
      - /docker/postgresql:/var/lib/postgresql

  analytics-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sharepool
      POSTGRES_DB: SharePool

    volumes:
      - /docker/postgresql:/var/lib/postgresql

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "sharepool"
      RABBITMQ_DEFAULT_PASS: "sharepool"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"